### ISSUE TITLE
CHTSync taking long in refreshes

### ISSUE THREAD

**Issue by billwambua** [medic/cht-pipeline#13]
When I recreated the `dbt` schema and ran the brac config from an empty schema, after the initial rebuild, subsequent refreshes are now taking very long. Initially they were taking less than 2 minutes, now they are taking up to 6hours, almost the same time as a build.
Before
[tmux-history-chtsync-0-0-20220820T050708.log](https://github.com/medic/cht-pipeline/files/9445720/tmux-history-chtsync-0-0-20220820T050708.log)

After
[tmux-log.log](https://github.com/medic/cht-pipeline/files/9445715/tmux-log.log)

cc @njogz @derickl

**Comment by derickl** [comment]
@billwambua Could you run an explain on the actual query being executed to get more insights on why it's taking long?

**Comment by andrablaj** [comment]
@witash is this error still happening? (this issue is very old). If not, can we close the ticket?

**Comment by njuguna-n** [comment]
@andrablaj this is likely to be fixed with the new schema in the base models and how we recommend handling form models and aggregations so it can be closed.
