### ISSUE TITLE
Add root model back to dbt

### ISSUE THREAD

**Issue by witash** [medic/cht-pipeline#139]
As part of #90 , the 'root model' was removed from base models, to avoid duplicate storage and data copying.
But the 'type' field still needs to be stored as its own column and indexed.
We could add this to couch2pg, but ideally couchdb should only know about the document, not anything about its contents.

To avoid copying the large jsonb column, we could have this root table only contain the type, uuid (and any other metadata that's useful) and still have downstream models join to the couch2pg table to access the document itself.

**Comment by njuguna-n** [comment]
@witash can we close this issue since the [document_metadata](https://github.com/medic/cht-pipeline/blob/main/models/root/document_metadata.sql) model was added?
