### ISSUE TITLE
Document how to test project specific DBT models

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-pipeline#150]
DBT offers multiple ways to test the models created including [data](https://docs.getdbt.com/docs/build/data-tests) and [unit](https://docs.getdbt.com/docs/build/unit-tests) tests. Many community members using cht-pipeline will likely be working with DBT for the first time so providing clear instructions on what to test and how to test it will make adoption of cht-pipeline much easier.

The purpose of this ticket is to come up with and document recommended testing practices for DBT models likely to be written for projects making use of cht-pipeline.

**Comment by njuguna-n** [comment]
Hi @lorerod my idea of the testing recommendations to make were:

- Have schema tests for all models and specifically enforcing `unique`, `not_null`, and `relationships` where relevant. (All models should have these tests)
- Add custom data tests for aggregation models to ensure the data is as expected (Only specific models need these tests)
- Add unit tests for complex logic e.g. data math, window functions e.t.c. (not required but good to have especially if model is covered by data tests)

What do you think of this general structure?

**Comment by lorerod** [comment]
Hi @njuguna-n I'm adding a section with testing recommendations for cht-pipeline. The [PR](https://github.com/medic/cht-docs/pull/1508) is ready for review.

**Comment by lorerod** [comment]
closed by [cht-docs PR #1508](https://github.com/medic/cht-docs/pull/1508)
