### ISSUE TITLE
Add users meta base models

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-pipeline#180]
**What feature do you want to improve?**
Add `medic-users-meta` models from [cht-couch2pg](https://github.com/medic/cht-couch2pg/tree/main/libs/medic-users-meta/migrations)

**Describe the improvement you'd like**
We should make existing user base models available as a part of cht-sync adn cht-pipleine as they were required and being used everywhere. 

**Describe alternatives you've considered**
Continue using cht-couch2pg.

**Additional context**

**Comment by garethbowen** [comment]
@andrablaj Is this the right repo for this issue?

**Comment by njuguna-n** [comment]
@garethbowen yes it is.

**Comment by njuguna-n** [comment]
@1yuv would you be able to add the required models? We have [documentation](https://docs.communityhealthtoolkit.org/hosting/analytics/building-dbt-models/) on getting started with dbt modeling and the Ecosystem team would be happy to support you if you get stuck.

**Comment by 1yuv** [comment]
Hi @njuguna-n , sadly I don't have bandwidth to work on this. But, this is critical for us if we are to consider moving any existing projects from couch2pg to cht-sync. For anyone working on this, they should also watch out medic/cht-sync#176 as well as that will determine where the medic-users-meta would be stored. Also solving medic/cht-sync#165 would make it easier for anyone to implement.
