### ISSUE TITLE
Handle deleted documents

### ISSUE THREAD

**Issue by njogz** [medic/cht-pipeline#19]
There are a couple of questions on how cht-sync should handle data since it logs each document revision:

- Figuring out a pattern to query the most relevant data 
- What happens when data is deleted? Given how data is re-used across views, there likely needs to be a pattern to help with these operations as well.

Relevant [slack](https://medic.slack.com/archives/C02N5UGRABF/p1686681340162779?thread_ts=1686680329.437519&cid=C02N5UGRABF) thread

**Comment by andrablaj** [comment]
From @samuelimoisili : Proposed Strategy: Ignoring deleted documents in queries

**Comment by andrablaj** [comment]
@njuguna-n @dianabarsan can we consider this issue done via https://github.com/medic/cht-sync/issues/112, or is there anything else to implement regarding deleted documents?

**Comment by njuguna-n** [comment]
@andrablaj yes, we can consider this as done.

**Comment by andrablaj** [comment]
Duplicate of https://github.com/medic/cht-sync/issues/112
