### ISSUE TITLE
Have models in reports_tables folder be incremental models

### ISSUE THREAD

**Issue by njogz** [medic/cht-pipeline#20]
Two models defined in the `reports_tables` folder are failing with the error described [here](https://github.com/medic/cht-pipeline/pull/16#discussion_r1197988476). The `types/data_record` has the same query but that one passes without any errors. To unblock the PR I made the change to have the models create regular tables but incremental tables are ideal for performance reasons.

**Comment by andrablaj** [comment]
@njuguna-n what is the status of this issue? Is it still relevant?

**Comment by njuguna-n** [comment]
@andrablaj this is still not addressed and still relevant so let's keep the issue open.
