### ISSUE TITLE
BRAC dbt Models

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-pipeline#25]
Create te DBT models to replicate the data produced by [these](https://github.com/medic/config-brac/tree/master/postgres) models.

**Comment by andrablaj** [comment]
@njuguna-n I see this issue was moved to the `Done` column, but the tests are still WIP. Moving it back to `In Progress` until we finalize that work.

**Comment by njuguna-n** [comment]
@andrablaj the PR was closed because we decided to use the `BRAC-models` as the main branch for all model related work.

**Comment by andrablaj** [comment]
As discussed in [Slack](https://medic.slack.com/archives/C03SP4KRVEX/p1699012582714919), I am closing this ticket.
