### ISSUE TITLE
Number of children aged less than 5 years who died

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-pipeline#50]
**Dashboards**: Under 5 deaths

Widget is a label titled U5 deaths

**Progress**:
- [ ] Models built
- [ ] **Testing**
     - [ ] Unit tests added
     - [ ] Validated with app services
- [ ] Widget/chat view built on dashboards

**Comment by andrablaj** [comment]
@Phil-Mwago, as this was removed from Product Team Activities, I guess that it is not relevant anymore? I will close it.
