### ISSUE TITLE
Investigate slow queries in the MoH Ug cht-sync instance

### ISSUE THREAD

**Issue by Phil-Mwago** [medic/cht-pipeline#53]

**Comment by lorerod** [comment]
@njuguna-n @Phil-Mwago, could you please provide additional context about this issue? I would be happy to help you in any way I can.

**Comment by njuguna-n** [comment]
I think we can safely close this one for now @lorerod. The main issue was the timeouts we were getting on superset so this ticket was meant to investigate and find out if slow DBT queries could have been culprits. Moving to an instance with more RAM seems to have solved the issue so the investigation is not as relevant anymore. Additionally, switching to the incremental models seems to be faster as well.

**Comment by andrablaj** [comment]
@njuguna-n Per your comment above, closing this issue, as moving it to `Done` doesn't close it automatically.
