### ISSUE TITLE
BRAC - Models failing after first run

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-pipeline#67]
Models defined in the `BRAC-models` branch are failing after the first run see screenshots below.

First run completes without issue
![Image](https://github.com/medic/cht-pipeline/assets/141340177/0d003988-dba3-43bf-b91b-6cda585e9a25)

Subsequent runs fail with the error below
![Image](https://github.com/medic/cht-pipeline/assets/141340177/e2f8aa50-e16f-46b1-88f7-0d0465b7da71)

**Comment by njuguna-n** [comment]
@lorerod I looked into this a bit yesterday and you can see what I tried with commits like [this one](https://github.com/medic/cht-pipeline/pull/68/commits/7825fefe66e790d1e2c1a44fb4468c229d4d0434) so hopefully that will save you from trying the same things.

**Comment by andrablaj** [comment]
@lorerod this issue is marked as `Done`. Should we close it?

**Comment by andrablaj** [comment]
Closing as marked as `Done`.
