### ISSUE TITLE
Add a way to do a full refresh when running DBT

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-pipeline#78]
There is currently no easy way to do  a full refresh on a cht-pipeline instance that is already running. This means that schema changes especially to incremental tables are not picked up. See this [comment](https://github.com/medic/cht-pipeline/issues/64#issuecomment-2041598518) here for an example of this.

**Comment by andrablaj** [comment]
@njuguna-n @witash, was this solved by https://github.com/medic/cht-sync/pull/94?

**Comment by andrablaj** [comment]
@witash @njuguna-n is this issue still relevant?

**Comment by njuguna-n** [comment]
@andrablaj this has been solved by [cht-sync#94](https://github.com/medic/cht-sync/pull/94) like you noted above.
