### ISSUE TITLE
Don't use a `couchdb` materialized view

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-pipeline#84]
All of the dbt models depend on one root model `couchdb`, which is a materialized view of the main table that gets data through cht-sync. 

https://github.com/medic/cht-pipeline/blob/main/models/root/couchdb.sql#L13

We should not use materialized views (at all?) and especially not as the main source of data for our models. 
We should build our dbt models over the original table that holds data from `cht-sync` directly.

**Comment by njuguna-n** [comment]
@dianabarsan this is no longer the case, can we close this issue?

**Comment by dianabarsan** [comment]
<3
