### ISSUE TITLE
Using the max_existing_timestamp macros on a new table throws an error

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-pipeline#87]
When starting a new sync process all models using the `max_existing_timestamp` throw the error below. The error is not thrown if the tables have already been created and have some data.

```
invalid input syntax for type timestamp: "None"
  LINE 38:   AND "@timestamp" >= CAST('None' AS TIMESTAMP)
```

**Comment by lorerod** [comment]
@njuguna-n did you tried with the changes made in `max_existing_multiro_macros.sql` in [this](https://github.com/medic/cht-pipeline/pull/81/commits/4df2d18e103fe4da79c5f413e3326e9a3dcfb5b5) commit?

**Comment by njuguna-n** [comment]
@lorerod yes. I have also tried using`Null` instead of None

**Comment by andrablaj** [comment]
Closing this issue as it was marked as `Done` and the [related PR](https://github.com/medic/cht-pipeline/pull/91#event-13060052707) was merged.
