### ISSUE TITLE
Create video on CHT Data Pipeline

### ISSUE THREAD

**Issue by billwambua** [medic/cht-pipeline#9]
Create a video that someone can use to quickly get into cht data pipeline.

The video should have an overview of:

- What is CHT Data Pipeline and what are its components.
- How to download and install CHTSync to a linux system.
- How to create your first DBT model and run it via CHTSync.
- Overview of incremental models vs 'normal' models.
- Indexes in DBT.

**Comment by andrablaj** [comment]
@billwambua is this something you are still planning to do? 
FYI @Phil-Mwago @njogz @samuelimoisili

**Comment by billwambua** [comment]
@andrablaj I am currently not working on CHT Pipeline. But when I get back on the project I will work on this.

It will be a good resource for onboarding any new members to the squad.

**Comment by andrablaj** [comment]
Thanks @billwambua! We can join forces with @medic/ecosystem when this is ready to be demoed!

**Comment by andrablaj** [comment]
There are [ongoing efforts](https://github.com/medic/cht-docs/issues/1297) for documenting CHT Sync & CHT Pipeline, some which live already so we can close this ticket.
