### ISSUE TITLE
Benchmark DBT model performance with expected MoH KE traffic and real world models

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-pipeline#96]
As stated in this [summary](https://github.com/medic/cht-sync/issues/108#issuecomment-2145134963) and emphasized in this [comment](https://github.com/medic/cht-sync/issues/108#issuecomment-2150419603) the benchmark tests that were done were based on a limited number of models and the performance and there is a need to run similar benchmark tests with more models defined.

**Comment by andrablaj** [comment]
Related: #140

**Comment by andrablaj** [comment]
@witash, it would be helpful to summarize the findings related to this ticket, such as the number of documents, the setup, the time the sync took, etc., for posterity.
